apiVersion: broker.amq.io/v2alpha1
kind: ActiveMQArtemis
metadata:
  name: broker-amq-mqtt
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acceptors:
    - expose: true
      name: all
      port: 61616
    - expose: true
      name: mqtt
      port: 1883
      protocols: mqtt
  addressSettings: {}
  adminPassword: admin
  adminUser: admin
  console:
    expose: true
  deploymentPlan:
    size: 1
    podSecurity: {}
    resources: {}
    readinessProbe: {}
    messageMigration: false
    extraMounts: {}
    managementRBACEnabled: true
    livenessProbe: {}
    journalType: aio
    enableMetricsPlugin: true
    storage: {}
  upgrades:
    enabled: false
    minor: false
  version: 7.9.1